// SPDX-License-Identifier: MPL-2.0
use super::*;
use crate::game::ability_scaling::spell_power_value;
use rfb_protocol::{AbilityEffectResolutionDto, ItemChargesDto, VirtueKindDto};

fn cast_where(
    base: &Game,
    id: &str,
    target: TargetSelection,
    accepts: impl Fn(&Game, &[DomainEvent]) -> bool,
) -> (Game, Vec<DomainEvent>) {
    for seed in 0..4096 {
        let mut before = base.clone();
        before.rng = RfbRng::seeded(seed);
        for pool in before.resources.values_mut() {
            pool.current = pool.maximum;
        }
        let mut trial = before.clone();
        let mut events = Vec::new();
        trial
            .resolve_player_ability(
                id,
                target.clone(),
                &mut events,
                &mut BTreeSet::new(),
                &mut Vec::new(),
            )
            .unwrap();
        if !accepts(&trial, &events) {
            continue;
        }
        let mut restored =
            Game::from_save_with_content(before.to_save(), before.content.clone()).unwrap();
        let mut resumed = Vec::new();
        restored
            .resolve_player_ability(
                id,
                target.clone(),
                &mut resumed,
                &mut BTreeSet::new(),
                &mut Vec::new(),
            )
            .unwrap();
        assert!(accepts(&restored, &resumed));
        assert_eq!(trial.rng, restored.rng);
        assert_eq!(trial.state_hash(), restored.state_hash());
        let saved =
            Game::from_save_with_content(restored.to_save(), restored.content.clone()).unwrap();
        assert_eq!(saved.state_hash(), restored.state_hash());
        return (restored, resumed);
    }
    panic!("no real cast seed satisfies {id}");
}

#[test]
fn ch3_ordinary_third_book_is_acquired_saved_and_cast() {
    let mut game = caster("high-mage", 50);
    let context = LootContext {
        table_id: "demo.loot-table.base-items".into(),
        floor_id: game.current_floor_id.clone(),
        depth: 45,
        source: LootSource::ItemUse {
            item_id: "test.ordinary-pool".into(),
        },
    };
    let draft = (0..16_384)
        .find_map(|_| {
            game.generate_one_loot_draft(&context, ItemGenerationMode::Ordinary)
                .filter(|d| d.kind_id == "demo.item.chaos-channels")
        })
        .expect("third Chaos book must be generated by the ordinary pool");
    let item = game
        .commit_generated_item_draft(draft, ItemLocation::Ground(game.player.position))
        .unwrap();
    let item_id = item.id.clone();
    game.items.push(item);
    game.pick_up_item_at_player(Some(&item_id)).unwrap();
    game = Game::from_save_with_content(game.to_save(), game.content.clone()).unwrap();
    let id = learn(&mut game, "chain-lightning");
    target(&mut game);
    cast_saved(&mut game, &id, TargetSelection::SelfTarget);
    assert!(game.entities[0].hp < 10_000);
    let book = game.content.item("demo.item.chaos-channels").unwrap();
    assert_eq!(book.rfb_base_kind.as_ref().unwrap().source_index, 514);
    assert_eq!(book.elemental_destruction_immunities.len(), 4);
}

#[test]
fn ch3_chain_lightning_hits_all_compass_rays_and_keeps_ten_damage_rolls() {
    let mut base = caster("high-mage", 40);
    let id = learn(&mut base, "chain-lightning");
    let directions = [
        Direction::SouthWest,
        Direction::South,
        Direction::SouthEast,
        Direction::West,
        Direction::East,
        Direction::NorthWest,
        Direction::North,
        Direction::NorthEast,
    ];
    for (i, direction) in directions.into_iter().enumerate() {
        let (dx, dy) = direction.delta();
        let actor = base.generated_actor(
            format!("test.ray-{i}"),
            "demo.actor.war-bear",
            Position {
                x: 10 + 2 * dx,
                y: 10 + 2 * dy,
            },
        );
        base.entities.push(actor);
    }
    let behind = base.generated_actor(
        "test.behind".into(),
        "demo.actor.war-bear",
        Position { x: 13, y: 10 },
    );
    base.entities.push(behind);
    let wall = base.index(Position { x: 9, y: 10 }).unwrap();
    base.terrain[wall] = "demo.terrain.wall".into();
    let events = cast_saved(&mut base, &id, TargetSelection::SelfTarget);
    assert_eq!(
        events
            .iter()
            .filter(|e| matches!(e, DomainEvent::AbilityBeamDamage { .. }))
            .count(),
        8
    );
    for actor in &base.entities {
        assert_eq!(
            actor.hp < actor.max_hp,
            actor.id != "test.ray-3",
            "{}",
            actor.id
        );
    }

    // No actors or items: the sole RNG draws are the ten independent 9d8 rolls.
    clear_monsters(&mut base);
    base.items
        .retain(|item| !matches!(item.location, ItemLocation::Ground(_)));
    let mut ability = base.content.ability(&id).unwrap().clone();
    Game::apply_player_spell_power(&mut ability, base.effective_player_spell_power_bonus());
    base.rng = RfbRng::seeded(731);
    let mut expected = base.rng.clone();
    for _ in 0..90 {
        expected.bounded(8);
    }
    base.resolve_player_chain_lightning_effect(
        &ability,
        &mut Vec::new(),
        &mut BTreeSet::new(),
        &mut Vec::new(),
    )
    .unwrap();
    assert_eq!(base.rng, expected);
}

#[test]
fn ch3_disintegration_radius_and_rocket_collision_use_actual_damage() {
    for (slug, level, radius) in [
        ("disintegrate", 39, 3),
        ("disintegrate", 40, 4),
        ("magic-rocket", 50, 2),
    ] {
        let mut game = caster("high-mage", level);
        ch2::dungeon(&mut game);
        let id = learn(&mut game, slug);
        target(&mut game);
        let wall_position = Position { x: 12, y: 11 };
        let wall = game.index(wall_position).unwrap();
        game.terrain[wall] = "demo.terrain.wall".into();
        // Rockets stop at the intervening actor even for a chosen position.
        let selected = if slug == "magic-rocket" {
            Position { x: 16, y: 10 }
        } else {
            Position { x: 12, y: 10 }
        };
        let profile = game.casting_profile().unwrap();
        let bonus = profile.spell_damage_bonus_base
            + profile.spell_damage_bonus_per_level
                * (level / u16::from(profile.spell_damage_bonus_level_divisor))
            + game.armor_spell_damage_bonus();
        let damage = if slug == "magic-rocket" {
            50 + 4 * level
        } else {
            70 + level
        };
        let expected = spell_power_value(
            u64::from(damage + bonus),
            game.effective_player_spell_power_bonus(),
        ) as i32;
        let events = cast_saved(
            &mut game,
            &id,
            TargetSelection::Position { position: selected },
        );
        let resolution = events
            .iter()
            .find_map(|e| match e {
                DomainEvent::AbilityAreaDamage { resolution, .. } => Some(resolution),
                _ => None,
            })
            .unwrap();
        assert_eq!(resolution.radius, radius);
        assert_eq!(resolution.base_raw_damage, expected);
        assert_eq!(resolution.center, Position { x: 12, y: 10 });
        assert_eq!(10_000 - game.entities[0].hp, expected);
        if slug == "disintegrate" {
            assert_ne!(game.terrain[wall], "demo.terrain.wall");
        }
    }
}

#[test]
fn ch3_polymorph_commits_a_real_form_and_survives_save() {
    let mut base = caster("high-mage", 50);
    let id = learn(&mut base, "polymorph-other");
    target(&mut base);
    let (game, _) = cast_where(
        &base,
        &id,
        TargetSelection::Direction {
            direction: Direction::East,
        },
        |_, events| {
            events.iter().any(|e| matches!(e, DomainEvent::AbilityEffectsResolved { resolution, .. }
            if resolution.effects.iter().any(|e| matches!(e, AbilityEffectResolutionDto::PolymorphTarget { changed: true, .. }))))
        },
    );
    assert_eq!(game.entities[0].id, base.entities[0].id);
    assert_ne!(game.entities[0].kind_id, base.entities[0].kind_id);
    assert_eq!(game.entities[0].position, base.entities[0].position);
    assert!(game.entities[0].hp > 0 && game.entities[0].hp <= game.entities[0].max_hp);
}

#[test]
fn ch3_arcane_binding_spends_mana_on_real_recharge_success_and_failure() {
    let mut base = caster("high-mage", 50);
    let id = learn(&mut base, "arcane-binding");
    assert!(
        base.snapshot()
            .player
            .abilities
            .iter()
            .find(|a| a.id == id)
            .unwrap()
            .item_selection_cancel_target
            .is_none()
    );
    give_inventory_item(&mut base, "test.device", "demo.item.detect-objects-staff");
    let item = base
        .items
        .iter_mut()
        .find(|i| i.id == "test.device")
        .unwrap();
    item.activation.as_mut().unwrap().device_check_difficulty = 120;
    item.charges = Some(ItemChargesDto {
        current: 10,
        maximum: 100,
    });
    let mut cancelled = base.clone();
    let rng = cancelled.rng.clone();
    let resources = cancelled.resources.clone();
    cancelled
        .resolve_player_ability(
            &id,
            TargetSelection::SelfTarget,
            &mut Vec::new(),
            &mut BTreeSet::new(),
            &mut Vec::new(),
        )
        .unwrap();
    assert_eq!(cancelled.rng, rng);
    assert_eq!(cancelled.resources, resources);
    for succeeded in [false, true] {
        let (game, events) = cast_where(
            &base,
            &id,
            TargetSelection::Item {
                item_id: "test.device".into(),
            },
            |_, events| {
                events.iter().any(|e| matches!(e, DomainEvent::DeviceRechargeResolved { succeeded: actual, .. } if *actual == succeeded))
            },
        );
        let attempted = events
            .iter()
            .find_map(|e| match e {
                DomainEvent::DeviceRechargeResolved {
                    attempted,
                    target_before,
                    target_after,
                    source_destroyed,
                    ..
                } => {
                    assert_eq!(*target_before, 10);
                    assert!(!source_destroyed);
                    assert_eq!(*target_after, if succeeded { 10 + attempted } else { 0 });
                    Some(*attempted)
                }
                _ => None,
            })
            .unwrap();
        let mana = &game.resources["demo.resource.mana"];
        assert_eq!(
            attempted,
            90.min(spell_power_value(90, base.effective_player_spell_power_bonus()) as u32)
        );
        assert!(mana.maximum - mana.current > attempted);
    }
    let (failed, events) = cast_where(
        &base,
        &id,
        TargetSelection::Item {
            item_id: "test.device".into(),
        },
        |_, events| {
            events
                .iter()
                .any(|e| matches!(e, DomainEvent::AbilityCastFailed { .. }))
        },
    );
    assert!(
        !events
            .iter()
            .any(|e| matches!(e, DomainEvent::DeviceRechargeResolved { .. }))
    );
    assert_eq!(
        failed
            .items
            .iter()
            .find(|i| i.id == "test.device")
            .unwrap()
            .charges
            .unwrap()
            .current,
        10
    );
}

#[test]
fn ch3_alter_reality_countdown_resumes_and_rebuilds_the_same_floor() {
    let mut base = caster("high-mage", 50);
    ch2::dungeon(&mut base);
    let id = learn(&mut base, "alter-reality");
    cast_saved(&mut base, &id, TargetSelection::SelfTarget);
    assert!((15..=35).contains(&base.reality_change_ticks));
    let mut cancelled = base.clone();
    cast_saved(&mut cancelled, &id, TargetSelection::SelfTarget);
    assert_eq!(cancelled.reality_change_ticks, 0);
    let floor_id = base.current_floor_id.clone();
    let terrain = base.terrain.clone();
    let mut resumed = Game::from_save_with_content(base.to_save(), base.content.clone()).unwrap();
    for _ in 0..base.reality_change_ticks {
        for game in [&mut base, &mut resumed] {
            game.advance_reality_change(&mut Vec::new(), &mut BTreeSet::new(), &mut Vec::new())
                .unwrap();
        }
    }
    assert_eq!(base.current_floor_id, floor_id);
    assert_ne!(base.terrain, terrain);
    assert_eq!(base.reality_change_ticks, 0);
    assert_eq!(base.state_hash(), resumed.state_hash());
    assert_eq!(base.rng, resumed.rng);
}

#[test]
fn ch3_branding_uses_a_real_chaos_ego_and_cancel_still_pays() {
    let mut base = caster("high-mage", 50);
    let id = learn(&mut base, "chaos-branding");
    assert_eq!(
        base.snapshot()
            .player
            .abilities
            .iter()
            .find(|a| a.id == id)
            .unwrap()
            .item_selection_cancel_target,
        Some(TargetSelection::SelfTarget)
    );
    give_inventory_item(&mut base, "test.weapon", "demo.item.dagger");
    let mut cancelled = base.clone();
    cast_saved(&mut cancelled, &id, TargetSelection::SelfTarget);
    assert!(
        cancelled.resources["demo.resource.mana"].current
            < cancelled.resources["demo.resource.mana"].maximum
    );
    assert!(
        cancelled
            .items
            .iter()
            .find(|i| i.id == "test.weapon")
            .unwrap()
            .affix_ids
            .is_empty()
    );
    let virtue = base.virtue_current(VirtueKindDto::Enchantment);
    cast_saved(
        &mut base,
        &id,
        TargetSelection::Item {
            item_id: "test.weapon".into(),
        },
    );
    let item = base.items.iter().find(|i| i.id == "test.weapon").unwrap();
    assert_eq!(item.affix_ids, ["rfb-legacy.affix.chaos"]);
    assert_eq!(item.discount_percent, 99);
    assert!(!item.rolled_affixes.is_empty());
    assert_eq!(base.virtue_current(VirtueKindDto::Enchantment), virtue + 2);
    assert!(base.item_property_knowledge["test.weapon"].identified);
    for item in &mut base.items {
        if matches!(item.location, ItemLocation::Equipped { .. }) {
            item.location = ItemLocation::Inventory;
        }
    }
    base.items
        .iter_mut()
        .find(|i| i.id == "test.weapon")
        .unwrap()
        .location = ItemLocation::Equipped {
        slot_id: "weapon".into(),
    };
    target(&mut base);
    base.entities[0].position = Position { x: 11, y: 10 };
    let mut hit = false;
    for seed in 0..256 {
        let mut game = base.clone();
        game.rng = RfbRng::seeded(seed);
        let mut restored =
            Game::from_save_with_content(game.to_save(), game.content.clone()).unwrap();
        for trial in [&mut game, &mut restored] {
            trial
                .resolve_player_melee(
                    0,
                    true,
                    &mut Vec::new(),
                    &mut BTreeSet::new(),
                    &mut Vec::new(),
                )
                .unwrap();
        }
        assert_eq!(game.state_hash(), restored.state_hash());
        if game.entities[0].hp < 10_000 {
            // Same enchanted dagger and same attack rolls, without the Chaos Ego.
            let mut plain = base.clone();
            let weapon = plain
                .items
                .iter_mut()
                .find(|i| i.id == "test.weapon")
                .unwrap();
            weapon.affix_ids.clear();
            weapon.rolled_affixes.clear();
            plain.rng = RfbRng::seeded(seed);
            plain
                .resolve_player_melee(
                    0,
                    true,
                    &mut Vec::new(),
                    &mut BTreeSet::new(),
                    &mut Vec::new(),
                )
                .unwrap();
            if game.entities[0].hp < plain.entities[0].hp {
                hit = true;
                break;
            }
        }
    }
    assert!(
        hit,
        "the Chaos brand must increase actual melee damage after save"
    );
}

#[test]
fn ch3_demon_summoning_preserves_pet_hostile_and_level_fifty_groups() {
    for (level, hostile, group) in [(49, false, false), (49, true, true), (50, false, true)] {
        let mut base = caster("high-mage", level);
        ch2::dungeon(&mut base);
        let id = learn(&mut base, "summon-demon");
        let (game, events) = cast_where(&base, &id, TargetSelection::SelfTarget, |_, events| {
            events.iter().any(|e| matches!(e, DomainEvent::AbilitySummoned { resolution, .. }
                if resolution.hostile == hostile && resolution.group == group && !resolution.entity_ids.is_empty()))
        });
        let resolution = events
            .iter()
            .find_map(|e| match e {
                DomainEvent::AbilitySummoned { resolution, .. } => Some(resolution),
                _ => None,
            })
            .unwrap();
        for id in &resolution.entity_ids {
            let actor = game.entities.iter().find(|a| a.id == *id).unwrap();
            let definition = game.content.actor(&actor.kind_id).unwrap();
            assert!(definition.level <= u32::from(3 * level / 2));
            assert_eq!(
                actor.controller_id.as_deref(),
                (!hostile).then_some(game.player.id.as_str())
            );
            assert!(actor.summon.is_none());
        }
        if !group {
            assert_eq!(resolution.entity_ids.len(), 1);
        } else {
            assert!(resolution.entity_ids.len() > 1);
        }
    }
}

#[test]
fn ch3_demon_summoning_with_no_space_still_spends_the_cast() {
    let mut base = caster("high-mage", 50);
    ch2::dungeon(&mut base);
    let id = learn(&mut base, "summon-demon");
    for y in 8..=12 {
        for x in 8..=12 {
            let position = Position { x, y };
            if position != base.player.position {
                let index = base.index(position).unwrap();
                base.terrain[index] = "demo.terrain.permanent-wall".into();
            }
        }
    }
    let (game, _) = cast_where(&base, &id, TargetSelection::SelfTarget, |_, events| {
        events.iter().any(|event| {
            matches!(event, DomainEvent::AbilitySummoned { resolution, .. }
            if resolution.entity_ids.is_empty())
        })
    });
    assert!(game.entities.is_empty());
    let mana = &game.resources["demo.resource.mana"];
    assert!(mana.current < mana.maximum);
}
