// SPDX-License-Identifier: MPL-2.0

import { FluentBundle, FluentResource, type FluentVariable } from "@fluent/bundle";

export const SUPPORTED_LOCALES = ["en-US", "zh-CN"] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

export const MESSAGE_KEYS = [
  "app-title",
  "app-eyebrow",
  "app-heading",
  "action-export-replay",
  "action-export-save",
  "action-load-save",
  "map-aria-label",
  "panel-map-title",
  "connection-starting",
  "connection-ready",
  "connection-error",
  "settings-input-label",
  "settings-tileset-label",
  "settings-camera-label",
  "settings-zoom-label",
  "settings-language-label",
  "language-name-en-us",
  "language-name-zh-cn",
  "input-preset-numpad",
  "input-preset-vi",
  "input-preset-wasd",
  "tileset-ascii",
  "tileset-image",
  "camera-full-map",
  "camera-player-centered",
  "zoom-75",
  "zoom-100",
  "zoom-125",
  "zoom-150",
  "zoom-200",
  "panel-status-title",
  "panel-task-log-title",
  "status-turn",
  "status-health",
  "status-health-value",
  "status-health-value-bonus",
  "status-attack",
  "status-defense",
  "status-stat-value",
  "status-stat-value-bonus",
  "status-effects",
  "status-effects-none",
  "status-effect-entry",
  "status-position",
  "status-hash",
  "panel-inventory-title",
  "inventory-stack-count",
  "inventory-weight-summary",
  "inventory-empty",
  "inventory-quantity",
  "inventory-selected-count",
  "inventory-equippable",
  "inventory-drop-quantity-label",
  "item-modifier-max-hp",
  "item-modifier-attack",
  "item-modifier-defense",
  "item-property-label",
  "item-quality-label",
  "item-quality-ordinary",
  "item-quality-fine",
  "item-quality-exceptional",
  "action-inventory-use",
  "action-inventory-appraise",
  "action-inventory-equip",
  "action-inventory-drop",
  "panel-equipment-title",
  "equipment-empty",
  "action-equipment-unequip",
  "equipment-slot-charm",
  "equipment-slot-unknown",
  "panel-native-save-title",
  "action-native-save-refresh",
  "native-save-name-label",
  "native-save-name-placeholder",
  "action-native-save-create",
  "action-native-save-load",
  "action-native-save-overwrite",
  "action-native-save-delete",
  "confirm-native-save-delete",
  "native-save-empty",
  "native-save-status-ready",
  "native-save-status-recoverable",
  "native-save-status-corrupt",
  "native-save-meta",
  "native-save-meta-unavailable",
  "native-save-date-unknown",
  "native-save-location-unknown",
  "panel-message-title",
  "action-clear-messages",
  "action-target-start",
  "action-target-cancel",
  "target-status-ready",
  "target-status-unavailable",
  "target-status-active",
  "controls-numpad",
  "controls-vi",
  "controls-wasd",
  "message-core-started",
  "message-input-preset-changed",
  "message-target-mode-started",
  "message-target-mode-cancelled",
  "message-target-mode-unavailable",
  "message-target-selection-invalid",
  "message-save-exported",
  "message-replay-exported",
  "message-crash-diagnostic-created",
  "message-save-loaded",
  "message-native-save-created",
  "message-native-save-overwritten",
  "message-native-save-loaded",
  "message-native-save-backup-loaded",
  "message-native-save-deleted",
  "message-native-save-failed",
  "native-save-error-name-invalid",
  "native-save-error-not-found",
  "native-save-error-corrupt",
  "native-save-error-unavailable",
  "message-tileset-load-failed",
  "message-error",
  "message-tileset-loaded",
  "message-tileset-image-too-small",
  "message-tileset-image-load-failed",
  "message-game-wait",
  "message-floor-transition",
  "message-floor-transition-unavailable",
  "message-floor-expedition-ended",
  "message-dungeon-guardian-defeated",
  "message-floor-one-shot-closed",
  "message-task-completed",
  "message-task-failed",
  "message-task-abandoned",
  "message-task-abandon-unavailable",
  "message-task-paused",
  "message-task-resumed",
  "message-task-rewarded",
  "task-log-entry",
  "task-log-retakes",
  "task-status-available",
  "task-status-active",
  "task-status-completed",
  "task-status-failed",
  "task-status-abandoned",
  "task-status-paused",
  "action-task-abandon",
  "message-door-mode-open",
  "message-door-mode-close",
  "message-door-mode-bash",
  "message-trap-mode-disarm",
  "message-terrain-mode-dig",
  "message-door-mode-cancelled",
  "message-terrain-interaction-mode-unavailable",
  "message-terrain-interaction-not-applicable",
  "message-terrain-interaction-blocked-actor",
  "message-terrain-interaction-blocked-item",
  "message-terrain-secret-discovered",
  "message-terrain-search-empty",
  "message-terrain-trap-triggered",
  "message-terrain-trap-disarmed",
  "message-terrain-trap-disarm-failed",
  "message-terrain-trap-disarm-unavailable",
  "message-terrain-dug",
  "message-terrain-dig-failed",
  "message-terrain-dig-unavailable",
  "message-door-opened",
  "message-door-unlocked",
  "message-door-unlock-failed",
  "message-door-open-unavailable",
  "message-door-bashed-open",
  "message-door-bash-failed",
  "message-door-bash-unavailable",
  "message-door-closed",
  "message-door-close-unavailable",
  "message-move-blocked",
  "message-combat-hit",
  "message-combat-hit-resisted",
  "message-combat-hit-amplified",
  "message-combat-hit-immune",
  "message-combat-slay",
  "message-combat-player-miss",
  "message-combat-monster-miss",
  "message-combat-monster-hit",
  "message-combat-monster-hit-resisted",
  "message-combat-monster-hit-amplified",
  "message-combat-monster-hit-immune",
  "message-combat-player-death",
  "message-projectile-unavailable",
  "message-projectile-ammo-unavailable",
  "message-projectile-target-unavailable",
  "message-projectile-landed",
  "message-projectile-miss",
  "message-projectile-hit",
  "message-projectile-slay",
  "message-projectile-ammo-recovered",
  "message-projectile-ammo-broken",
  "message-status-player-damage",
  "message-status-entity-damage",
  "message-status-player-expired",
  "message-status-entity-expired",
  "message-status-player-death",
  "message-status-entity-death",
  "message-status-fear-blocked",
  "message-item-pickup-success",
  "message-item-pickup-over-capacity",
  "message-item-pickup-none",
  "message-item-equip-success",
  "message-item-equip-swap",
  "message-item-equip-unavailable",
  "message-item-appraise-success",
  "message-item-appraise-unavailable",
  "message-item-property-discovered",
  "message-loot-drop",
  "message-item-unequip-success",
  "message-item-unequip-none",
  "message-item-drop-success",
  "message-item-drop-none",
  "message-item-use-heal",
  "message-item-use-no-effect",
  "message-item-use-unavailable",
  "message-item-thrown",
  "message-throw-miss",
  "message-throw-hit",
  "message-throw-slay",
  "message-item-throw-unavailable",
  "message-unknown-event",
  "item-demo-luminous-shard-name",
  "item-demo-unfamiliar-shard-name",
  "item-demo-echo-charm-name",
  "item-demo-echo-blade-name",
  "item-demo-echo-blade-description",
  "item-demo-resonance-sling-name",
  "item-demo-resonance-sling-description",
  "item-demo-resonance-pellet-name",
  "item-demo-resonance-pellet-description",
  "affix-demo-harmonic-edge-name",
  "affix-demo-harmonic-edge-description",
  "item-unknown-name",
  "actor-demo-ember-mote-name",
  "actor-demo-acid-seep-name",
  "actor-demo-storm-spark-name",
  "actor-demo-frost-wisp-name",
  "actor-demo-venom-spore-name",
  "actor-demo-echo-hound-name",
  "actor-demo-echo-hound-description",
  "actor-demo-resonant-warden-name",
  "actor-demo-resonant-warden-description",
  "actor-demo-chorus-captain-name",
  "actor-demo-chorus-captain-description",
  "actor-demo-spore-shepherd-name",
  "actor-demo-spore-shepherd-description",
  "actor-unknown-name",
  "status-poison-name",
  "status-bleeding-name",
  "status-haste-name",
  "status-slow-name",
  "status-stun-name",
  "status-fear-name",
  "status-unknown-name",
  "damage-type-physical-name",
  "damage-type-acid-name",
  "damage-type-electricity-name",
  "damage-type-fire-name",
  "damage-type-cold-name",
  "damage-type-poison-name",
  "world-demo-original-lab-name",
  "floor-demo-echo-depth-1-name",
  "floor-demo-echo-depth-2-name",
  "floor-demo-echo-depth-3-name",
  "floor-demo-resonance-depth-1-name",
  "floor-demo-resonance-depth-2-name",
  "floor-demo-resonance-depth-3-name",
  "floor-demo-resonance-depth-4-name",
  "floor-demo-resonance-depth-5-name",
  "floor-demo-resonance-depth-6-name",
  "floor-demo-resonance-depth-7-name",
  "floor-demo-resonance-depth-8-name",
  "floor-demo-resonance-depth-9-name",
  "floor-demo-resonance-depth-10-name",
  "terrain-demo-resonance-rift-name",
  "terrain-demo-resonance-rift-description",
  "terrain-demo-resonant-floor-name",
  "terrain-demo-resonant-floor-description",
  "terrain-demo-resonance-cavern-name",
  "terrain-demo-resonance-cavern-description",
  "terrain-demo-resonance-water-deep-name",
  "terrain-demo-resonance-water-deep-description",
  "terrain-demo-resonance-water-shallow-name",
  "terrain-demo-resonance-water-shallow-description",
  "terrain-demo-resonance-vein-name",
  "terrain-demo-resonance-vein-description",
  "terrain-demo-resonance-ruin-name",
  "terrain-demo-resonance-ruin-description",
  "vault-demo-harmonic-sepulcher-name",
  "vault-demo-resonant-gallery-name",
  "vault-demo-resonance-spindle-name",
  "vault-demo-resonance-crook-name",
  "vault-demo-sealed-resonance-monolith-name",
  "vault-demo-resonance-crossroads-name",
  "floor-demo-echo-task-rift-name",
  "terrain-demo-task-rift-name",
  "terrain-demo-task-rift-description",
  "terrain-demo-task-rift-closed-name",
  "terrain-demo-task-rift-closed-description",
  "terrain-demo-task-rift-failed-name",
  "terrain-demo-task-rift-failed-description",
  "terrain-demo-task-rift-abandoned-name",
  "terrain-demo-task-rift-abandoned-description",
  "floor-demo-echo-hunt-rift-name",
  "terrain-demo-hunt-rift-name",
  "terrain-demo-hunt-rift-description",
  "terrain-demo-hunt-rift-closed-name",
  "terrain-demo-hunt-rift-closed-description",
  "terrain-demo-hunt-rift-failed-name",
  "terrain-demo-hunt-rift-failed-description",
  "terrain-demo-hunt-rift-abandoned-name",
  "terrain-demo-hunt-rift-abandoned-description",
  "floor-demo-echo-bounty-rift-name",
  "terrain-demo-bounty-rift-name",
  "terrain-demo-bounty-rift-description",
  "terrain-demo-bounty-rift-closed-name",
  "terrain-demo-bounty-rift-closed-description",
  "terrain-demo-bounty-rift-failed-name",
  "terrain-demo-bounty-rift-failed-description",
  "terrain-demo-bounty-rift-abandoned-name",
  "terrain-demo-bounty-rift-abandoned-description",
  "floor-demo-echo-bounty-annex-rift-name",
  "terrain-demo-bounty-annex-rift-name",
  "terrain-demo-bounty-annex-rift-description",
  "terrain-demo-bounty-annex-rift-closed-name",
  "terrain-demo-bounty-annex-rift-closed-description",
  "terrain-demo-bounty-annex-rift-failed-name",
  "terrain-demo-bounty-annex-rift-failed-description",
  "terrain-demo-bounty-annex-rift-abandoned-name",
  "terrain-demo-bounty-annex-rift-abandoned-description",
  "floor-demo-echo-chain-rift-name",
  "floor-demo-echo-chain-vault-rift-name",
  "terrain-demo-chain-rift-name",
  "terrain-demo-chain-rift-description",
  "terrain-demo-chain-rift-closed-name",
  "terrain-demo-chain-rift-closed-description",
  "terrain-demo-chain-rift-failed-name",
  "terrain-demo-chain-rift-failed-description",
  "terrain-demo-chain-rift-abandoned-name",
  "terrain-demo-chain-rift-abandoned-description",
  "terrain-demo-chain-vault-rift-name",
  "terrain-demo-chain-vault-rift-description",
  "terrain-demo-chain-vault-rift-closed-name",
  "terrain-demo-chain-vault-rift-closed-description",
  "terrain-demo-chain-vault-rift-failed-name",
  "terrain-demo-chain-vault-rift-failed-description",
  "terrain-demo-chain-vault-rift-abandoned-name",
  "terrain-demo-chain-vault-rift-abandoned-description",
  "terrain-demo-stairs-down-name",
  "terrain-demo-stairs-down-description",
  "terrain-demo-stairs-up-name",
  "terrain-demo-stairs-up-description",
  "terrain-demo-shaft-down-name",
  "terrain-demo-shaft-down-description",
  "terrain-demo-shaft-up-name",
  "terrain-demo-shaft-up-description",
  "terrain-demo-door-closed-name",
  "terrain-demo-door-closed-description",
  "terrain-demo-door-locked-name",
  "terrain-demo-door-locked-description",
  "terrain-demo-door-secret-name",
  "terrain-demo-door-secret-description",
  "terrain-demo-door-broken-name",
  "terrain-demo-door-broken-description",
  "terrain-demo-door-open-name",
  "terrain-demo-door-open-description",
  "terrain-demo-trap-echo-snare-name",
  "terrain-demo-trap-echo-snare-description",
  "terrain-demo-echo-rubble-name",
  "terrain-demo-echo-rubble-description",
] as const;

export type MessageKey = (typeof MESSAGE_KEYS)[number];
export type LocalizationArgs = Record<string, FluentVariable>;
export type LocaleSources = Record<SupportedLocale, readonly string[]>;

export class Localization {
  readonly #bundles: Record<SupportedLocale, FluentBundle>;
  #locale: SupportedLocale;

  constructor(locale: SupportedLocale, sources: LocaleSources) {
    this.#locale = locale;
    this.#bundles = {
      "en-US": createBundle("en-US", sources["en-US"]),
      "zh-CN": createBundle("zh-CN", sources["zh-CN"]),
    };
  }

  get locale(): SupportedLocale {
    return this.#locale;
  }

  setLocale(locale: SupportedLocale): void {
    this.#locale = locale;
  }

  hasMessage(locale: SupportedLocale, key: MessageKey): boolean {
    return this.#bundles[locale].hasMessage(key);
  }

  format(key: MessageKey, args?: LocalizationArgs): string {
    return this.#formatFrom(this.#locale, key, args) ?? this.#formatFrom("en-US", key, args) ?? `[${key}]`;
  }

  localizeDocument(root: ParentNode = document): void {
    for (const element of root.querySelectorAll<HTMLElement>("[data-l10n-id]")) {
      const key = element.dataset.l10nId as MessageKey | undefined;
      if (key) element.textContent = this.format(key);
    }
    for (const element of root.querySelectorAll<HTMLElement>("[data-l10n-aria-label]")) {
      const key = element.dataset.l10nAriaLabel as MessageKey | undefined;
      if (key) element.setAttribute("aria-label", this.format(key));
    }
    document.documentElement.lang = this.#locale;
  }

  #formatFrom(locale: SupportedLocale, key: MessageKey, args?: LocalizationArgs): string | undefined {
    const bundle = this.#bundles[locale];
    const message = bundle.getMessage(key);
    if (!message?.value) return undefined;
    const errors: Error[] = [];
    const value = bundle.formatPattern(message.value, args, errors);
    if (errors.length > 0) {
      console.warn(`Fluent formatting error for ${locale}/${key}`, errors);
    }
    return value;
  }
}

export function isSupportedLocale(value: string | null): value is SupportedLocale {
  return SUPPORTED_LOCALES.some((locale) => locale === value);
}

function createBundle(locale: SupportedLocale, sources: readonly string[]): FluentBundle {
  const bundle = new FluentBundle(locale, { useIsolating: false });
  for (const source of sources) {
    const errors = bundle.addResource(new FluentResource(source));
    if (errors.length > 0) {
      throw new Error(`Invalid Fluent resource for ${locale}: ${errors.join("; ")}`);
    }
  }
  return bundle;
}
