// SPDX-License-Identifier: MPL-2.0
// @generated by `cargo run -p rfb-protocol --features bindings --bin generate-bindings`; do not edit.

export type Direction = "north" | "north-east" | "east" | "south-east" | "south" | "south-west" | "west" | "north-west";

export type GameCommand = { "type": "drop", itemIds: Array<string>, } | { "type": "drop-quantity", itemId: string, quantity: number, } | { "type": "equip", itemId: string, } | { "type": "move", direction: Direction, } | { "type": "pick-up" } | { "type": "unequip", slotId: string, } | { "type": "wait" };

export type GameCommandEnvelope = { commandSeq: number, expectedRevision: number, command: GameCommand, };

export type StatModifiersDto = { attack: number, defense: number, maxHp: number, };

export type DamageDiceDto = { dice: number, sides: number, damageType: DamageTypeDto, };

export type AttackProfileDto = { attacks: number, toHit: number, toDamage: number, damage: DamageDiceDto, sourceItemId?: string | null, };

export type Position = { x: number, y: number, };

export type CellDto = { position: Position, terrainId: string, itemId: string | null, actorId: string | null, };

export type VisibilityState = "visible" | "remembered" | "hidden";

export type CellLightDto = { color: number, intensity: number, };

export type CellVisualDto = { position: Position, visibility: VisibilityState, light: CellLightDto, };

export type ContentVisualDto = { id: string, glyph: string, };

export type DamageTypeDto = "physical" | "acid" | "electricity" | "fire" | "cold" | "poison";

export type ResistanceLevelDto = "vulnerable" | "normal" | "resistant" | "strong" | "immune";

export type ResistanceDto = { damageType: DamageTypeDto, level: ResistanceLevelDto, };

export type DamageResolutionDto = { rawDamage: number, armorReduction: number, resistanceAdjustment: number, finalDamage: number, damageType: DamageTypeDto, resistance: ResistanceLevelDto, };

export type GameEventOutcomeDto = { "type": "damage", resolution: DamageResolutionDto, } | { "type": "death", resolution: DamageResolutionDto, };

export type StatusDto = { kindId: string, intensity: number, remainingTicks: number, };

export type PlayerDto = { id: string, kindId: string, position: Position, hp: number, maxHp: number, speed: number, energyNeed: number, baseMaxHp: number, attack: number, baseAttack: number, defense: number, baseDefense: number, meleeSkill: number, armorClass: number, meleeDamage: DamageDiceDto, meleeProfile: AttackProfileDto, isDead: boolean, equipmentModifiers: StatModifiersDto, statuses: Array<StatusDto>, resistances: Array<ResistanceDto>, };

export type EntityDto = { id: string, kindId: string, position: Position, hp: number, maxHp: number, speed: number, energyNeed: number, attack: number, defense: number, meleeSkill: number, armorClass: number, meleeDamage: DamageDiceDto, meleeProfile: AttackProfileDto, statuses: Array<StatusDto>, };

export type ItemDto = { id: string, kindId: string, position: Position, quantity: number, };

export type InventoryItemDto = { id: string, kindId: string, quantity: number, equipmentSlot: string | null, modifiers: StatModifiersDto, meleeProfile?: AttackProfileDto | null, };

export type EquipmentItemDto = { id: string, kindId: string, quantity: number, slotId: string, modifiers: StatModifiersDto, meleeProfile?: AttackProfileDto | null, };

export type GameEventDto = { kind: string, messageKey: string, args: { [key in string]: string }, outcome?: GameEventOutcomeDto | null, };

export type GameSnapshot = { protocolVersion: string, revision: number, turn: number, worldTick: number, lastCommandSeq: number, width: number, height: number, cells: Array<CellDto>, visualCells: Array<CellVisualDto>, player: PlayerDto, entities: Array<EntityDto>, items: Array<ItemDto>, inventory: Array<InventoryItemDto>, equipment: Array<EquipmentItemDto>, contentId: string, contentHash: string, contentVisuals: Array<ContentVisualDto>, worldId: string, stateHash: string, };

export type GameUpdate = { baseRevision: number, revision: number, turn: number, worldTick: number, commandSeq: number, events: Array<GameEventDto>, changedCells: Array<CellDto>, changedVisualCells: Array<CellVisualDto>, player: PlayerDto, entities: Array<EntityDto>, items: Array<ItemDto>, inventory: Array<InventoryItemDto>, equipment: Array<EquipmentItemDto>, removedEntities: Array<string>, stateHash: string, };

