// SPDX-License-Identifier: MPL-2.0
// @generated by `cargo run -p rfb-protocol --features bindings --bin generate-bindings`; do not edit.

export type Direction = "north" | "north-east" | "east" | "south-east" | "south" | "south-west" | "west" | "north-west";

export type GameCommand = { "type": "abandon-task" } | { "type": "abandon-paused-task", taskId: string, } | { "type": "increase-attribute", attribute: AttributeKindDto, } | { "type": "appraise", itemId: string, } | { "type": "bash-door", direction: Direction, } | { "type": "cast-ability", abilityId: string, target: TargetSelection, } | { "type": "close-door", direction: Direction, } | { "type": "disarm-trap", direction: Direction, } | { "type": "dig-terrain", direction: Direction, } | { "type": "drop", itemIds: Array<string>, } | { "type": "drop-quantity", itemId: string, quantity: number, } | { "type": "equip", itemId: string, } | { "type": "fire", direction: Direction, } | { "type": "fire-target", target: TargetSelection, } | { "type": "move", direction: Direction, } | { "type": "open-door", direction: Direction, } | { "type": "pick-up" } | { "type": "retire" } | { "type": "rest", turns: number, } | { "type": "search" } | { "type": "forget-ability", abilityId: string, } | { "type": "study-ability", bookItemId: string, abilityId: string, } | { "type": "throw", itemId: string, direction: Direction, } | { "type": "traverse-stairs" } | { "type": "use-item", itemId: string, } | { "type": "unequip", slotId: string, } | { "type": "wait" };

export type GameCommandEnvelope = { commandSeq: number, expectedRevision: number, command: GameCommand, };

export type StatModifiersDto = { attack: number, defense: number, maxHp: number, strength: number, intelligence: number, wisdom: number, dexterity: number, constitution: number, charisma: number, };

export type AttributeKindDto = "strength" | "intelligence" | "wisdom" | "dexterity" | "constitution" | "charisma";

export type AttributeValueDto = { natural: number, effective: number, index: number, };

export type AttributeSetDto = { strength: AttributeValueDto, intelligence: AttributeValueDto, wisdom: AttributeValueDto, dexterity: AttributeValueDto, constitution: AttributeValueDto, charisma: AttributeValueDto, };

export type PlayerProgressDto = { level: number, maxLevel: number, experience: bigint, levelCap: number, attributeCap: number, attributeIndexCap: number, experienceForNextLevel?: bigint | null, pendingAttributeIncreases: number, victoryLevelCapUnlocked: boolean, attributes: AttributeSetDto, skills: Array<SkillProgressDto>, };

export type SkillProgressDto = { id: string, nameKey: string, current: number, maximum: number, base: number, growthPerTenLevels: number, };

export type PlayerBuildDto = { buildId: string, buildNameKey: string, raceId: string, raceNameKey: string, classId: string, classNameKey: string, personalityId: string, personalityNameKey: string, lifePercent: number, experiencePercent: number, };

export type DamageDiceDto = { dice: number, sides: number, damageType: DamageTypeDto, };

export type AttackProfileDto = { attacks: number, toHit: number, toDamage: number, damage: DamageDiceDto, sourceItemId?: string | null, };

export type MeleeBlowDto = { methodId: string, toHit: number, damage: DamageDiceDto, };

export type MeleeRoutineDto = { blows: Array<MeleeBlowDto>, };

export type TargetModeDto = "direction" | "position" | "entity" | "self";

export type TargetSpecDto = { modes: Array<TargetModeDto>, range: number, requiresLineOfEffect: boolean, };

export type ResourcePoolDto = { id: string, nameKey: string, current: number, maximum: number, waitRecoveryAmount: number, restRecoveryAmount: number, };

export type AbilityLearningDto = { learnedCount: number, capacity: number, remainingSlots: number, };

export type AbilityProficiencyRankDto = "unskilled" | "beginner" | "skilled" | "expert" | "master";

export type AbilityDto = { id: string, nameKey: string, descriptionKey: string, minimumLevel: number, resourceId: string, baseResourceCost: number, resourceCost: number, failurePercent: number, proficiency: number, proficiencyCap: number, proficiencyRank: AbilityProficiencyRankDto, castCount: number, failCount: number, cooldownRemaining: number, cooldownTurns: number, cooldownGroupId?: string | null, areaRadius?: number | null, beamDamage?: boolean, coneRadius?: number | null, targetSpec: TargetSpecDto, learned: boolean, bookItemId?: string | null, canStudy: boolean, canForget: boolean, canCast: boolean, };

export type TargetSelection = { "type": "direction", direction: Direction, } | { "type": "position", position: Position, } | { "type": "entity", entityId: string, } | { "type": "self" };

export type ProjectileProfileDto = { range: number, toHit: number, toDamage: number, damage: DamageDiceDto, ammoKindId: string, targetSpec: TargetSpecDto, sourceItemId: string, };

export type ThrowProfileDto = { range: number, toHit: number, toDamage: number, damage: DamageDiceDto, sourceItemId: string, };

export type ProjectileTraceDto = { origin: Position, impact: Position, landing: Position, traversed: Array<Position>, };

export type Position = { x: number, y: number, };

export type TerrainInteractionKindDto = "open-door" | "close-door" | "bash-door" | "disarm-trap" | "dig-terrain";

export type TerrainInteractionUnavailableReasonDto = "occupied-by-actor" | "occupied-by-item";

export type TerrainInteractionDto = { kind: TerrainInteractionKindDto, direction: Direction, position: Position, terrainId: string, requiresCheck: boolean, available: boolean, unavailableReason?: TerrainInteractionUnavailableReasonDto | null, };

export type TaskStatusKindDto = "abandoned" | "available" | "active" | "completed" | "failed" | "paused";

export type TaskStatusDto = { taskId: string, floorId: string, nameKey: string, status: TaskStatusKindDto, current: number, required: number, stage: number, stages: number, retakesUsed: number, maxRetakes?: number | null, };

export type CellDto = { position: Position, terrainId: string, itemId: string | null, actorId: string | null, };

export type VisibilityState = "visible" | "remembered" | "hidden";

export type CellLightDto = { color: number, intensity: number, };

export type CellVisualDto = { position: Position, visibility: VisibilityState, light: CellLightDto, };

export type ContentVisualDto = { id: string, glyph: string, };

export type DamageTypeDto = "physical" | "acid" | "electricity" | "fire" | "cold" | "poison";

export type ResistanceLevelDto = "vulnerable" | "normal" | "resistant" | "strong" | "immune";

export type ResistanceDto = { damageType: DamageTypeDto, level: ResistanceLevelDto, };

export type DamageResolutionDto = { rawDamage: number, armorReduction: number, resistanceAdjustment: number, finalDamage: number, damageType: DamageTypeDto, resistance: ResistanceLevelDto, };

export type CheckOutcomeDto = "automatic-success" | "automatic-failure" | "success" | "failure";

export type CheckResolutionDto = { skillId: string, ability: number, difficulty: number, percentileRoll: number, contestRoll?: number | null, threshold: number, outcome: CheckOutcomeDto, };

export type AbilityCastResolutionDto = { abilityId: string, resourceId: string, baseResourceCost: number, resourceCost: number, resourceBefore: number, resourceAfter: number, failurePercent: number, percentileRoll: number, succeeded: boolean, proficiencyBefore: number, proficiencyAfter: number, proficiencyRank: AbilityProficiencyRankDto, castCount: number, failCount: number, cooldownBefore: number, cooldownAfter: number, };

export type AbilityAreaDamageResolutionDto = { center: Position, radius: number, baseRawDamage: number, damageType: DamageTypeDto, affectedPositions: Array<Position>, targetCount: number, };

export type AbilityBeamDamageResolutionDto = { baseRawDamage: number, damageType: DamageTypeDto, affectedPositions: Array<Position>, targetCount: number, };

export type AbilityConeDamageResolutionDto = { radius: number, baseRawDamage: number, damageType: DamageTypeDto, affectedPositions: Array<Position>, targetCount: number, };

export type ResourceRecoveryResolutionDto = { resourceId: string, before: number, after: number, recovered: number, };

export type RestStopReasonDto = "damaged" | "enemy-visible" | "full-resources" | "invalid-turns" | "player-died" | "turn-limit";

export type RestResolutionDto = { requestedTurns: number, completedTurns: number, stopReason: RestStopReasonDto, resourceRecoveries: Array<ResourceRecoveryResolutionDto>, };

export type HealingResolutionDto = { requested: number, applied: number, };

export type GameEventOutcomeDto = { "type": "ability-area-damage", resolution: AbilityAreaDamageResolutionDto, } | { "type": "ability-beam-damage", resolution: AbilityBeamDamageResolutionDto, } | { "type": "ability-cone-damage", resolution: AbilityConeDamageResolutionDto, } | { "type": "ability-cast", resolution: AbilityCastResolutionDto, } | { "type": "check", resolution: CheckResolutionDto, } | { "type": "damage", resolution: DamageResolutionDto, } | { "type": "death", resolution: DamageResolutionDto, } | { "type": "heal", resolution: HealingResolutionDto, } | { "type": "resource-recovery", resolution: ResourceRecoveryResolutionDto, } | { "type": "rest", resolution: RestResolutionDto, };

export type StatusDto = { kindId: string, intensity: number, remainingTicks: number, };

export type PlayerDto = { id: string, kindId: string, position: Position, hp: number, maxHp: number, speed: number, energyNeed: number, carriedWeightTenthsPound: number, carryCapacityTenthsPound: number, baseMaxHp: number, attack: number, baseAttack: number, defense: number, baseDefense: number, meleeSkill: number, armorClass: number, meleeDamage: DamageDiceDto, meleeProfile: AttackProfileDto, projectileProfile?: ProjectileProfileDto | null, isDead: boolean, equipmentModifiers: StatModifiersDto, statuses: Array<StatusDto>, resistances: Array<ResistanceDto>, progress?: PlayerProgressDto, build?: PlayerBuildDto | null, resources?: Array<ResourcePoolDto>, abilityLearning?: AbilityLearningDto | null, abilities?: Array<AbilityDto>, };

export type EntityDto = { id: string, kindId: string, position: Position, hp: number, maxHp: number, speed: number, energyNeed: number, alerted: boolean, attack: number, defense: number, meleeSkill: number, armorClass: number, meleeDamage: DamageDiceDto, meleeProfile: AttackProfileDto, meleeRoutine: MeleeRoutineDto, statuses: Array<StatusDto>, };

export type ItemDto = { id: string, kindId: string, displayNameKey: string, knowledge: ItemKnowledgeDto, position: Position, quantity: number, };

export type ItemKnowledgeDto = "unknown" | "tried" | "aware";

export type ItemQualityDto = "ordinary" | "fine" | "exceptional";

export type ItemIdentificationDto = "unexamined" | "appraised" | "identified";

export type ItemPropertyDto = { affixId: string, nameKey: string, modifiers: StatModifiersDto, };

export type InventoryItemDto = { id: string, kindId: string, displayNameKey: string, knowledge: ItemKnowledgeDto, usable: boolean, quantity: number, weightTenthsPound: number, equipmentSlot: string | null, modifiers: StatModifiersDto, identification: ItemIdentificationDto, quality?: ItemQualityDto | null, knownProperties?: Array<ItemPropertyDto>, meleeProfile?: AttackProfileDto | null, projectileProfile?: ProjectileProfileDto | null, throwProfile?: ThrowProfileDto | null, };

export type EquipmentItemDto = { id: string, kindId: string, displayNameKey: string, knowledge: ItemKnowledgeDto, quantity: number, weightTenthsPound: number, slotId: string, modifiers: StatModifiersDto, identification: ItemIdentificationDto, quality?: ItemQualityDto | null, knownProperties?: Array<ItemPropertyDto>, meleeProfile?: AttackProfileDto | null, projectileProfile?: ProjectileProfileDto | null, throwProfile?: ThrowProfileDto | null, };

export type GameEventDto = { kind: string, messageKey: string, args: { [key in string]: string }, outcome?: GameEventOutcomeDto | null, trace?: ProjectileTraceDto | null, };

export type CampaignStatusDto = "active" | "victorious" | "retired";

export type CampaignStateDto = { status: CampaignStatusDto, score: bigint, conqueredDungeons: number, completedTasks: number, victoryTurn?: number | null, retiredTurn?: number | null, };

export type GameSnapshot = { protocolVersion: string, revision: number, turn: number, worldTick: number, lastCommandSeq: number, width: number, height: number, cells: Array<CellDto>, visualCells: Array<CellVisualDto>, player: PlayerDto, entities: Array<EntityDto>, items: Array<ItemDto>, inventory: Array<InventoryItemDto>, equipment: Array<EquipmentItemDto>, contentId: string, contentHash: string, contentVisuals: Array<ContentVisualDto>, worldId: string, floorId: string, dungeonInstanceId?: string | null, terrainInteractions: Array<TerrainInteractionDto>, tasks: Array<TaskStatusDto>, campaign: CampaignStateDto, stateHash: string, };

export type GameUpdate = { baseRevision: number, revision: number, turn: number, worldTick: number, commandSeq: number, floorId: string, dungeonInstanceId?: string | null, events: Array<GameEventDto>, changedCells: Array<CellDto>, changedVisualCells: Array<CellVisualDto>, player: PlayerDto, entities: Array<EntityDto>, items: Array<ItemDto>, inventory: Array<InventoryItemDto>, equipment: Array<EquipmentItemDto>, removedEntities: Array<string>, terrainInteractions: Array<TerrainInteractionDto>, tasks: Array<TaskStatusDto>, campaign: CampaignStateDto, stateHash: string, };

